import { Injectable } from '@nestjs/common';
import * as bcrypt from 'bcrypt';
import { JwtService } from '@nestjs/jwt'; // Make sure to import JwtService

@Injectable()
export class AuthService {
  constructor(
    private readonly jwtService: JwtService, // Inject JwtService for token creation
  ) {}

  // Register a new user
  async register(email: string, password: string) {
    // Check if user already exists (this should query your database)
    const existingUser = await this.findUserByEmail(email);
    if (existingUser) {
      throw new Error('User already exists');
    }

    // Hash the password before storing it
    const hashedPassword = await bcrypt.hash(password, 10);

    // Save the user to the database (mock example)
    const newUser = await this.createUser(email, hashedPassword);

    // Return a message indicating the registration was successful
    return { message: 'Registration successful', user: newUser };
  }

  // Login method (already implemented)
  async login(email: string, password: string) {
    // Authenticate the user (e.g., query your database to find the user)
    const user = await this.findUserByEmail(email);
    if (!user) {
      throw new Error('User not found');
    }

    // Verify the password
    const passwordMatch = await bcrypt.compare(password, user.password);
    if (!passwordMatch) {
      throw new Error('Invalid password');
    }

    // Create JWT token
    const token = this.jwtService.sign({ id: user.id, email: user.email });

    // Return an object containing the token and the user information
    return {
      message: 'Login successful',
      token: token,
      user: user,
    };
  }

  // Example method to find a user (replace this with actual logic to query the database)
  private async findUserByEmail(email: string) {
    // Mock user for example, replace with actual DB query
    return null; // Return null for demonstration, simulating that the user doesn't exist
  }

  // Example method to create a user (replace this with actual logic to store the user in your DB)
  private async createUser(email: string, password: string) {
    // Mocked new user
    return {
      id: 2,  // Assume this ID is generated by your DB
      email: email,
      password: password, // Store the hashed password
    };
  }
}
